---
apiVersion: v1
kind: Service
metadata:
  name: ksc-employee-mock
  labels:
    app: ksc-employee-mock
spec:
  selector:
    app: ksc-employee-mock
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksc-employee-mock
spec:
  selector:
    matchLabels:
      app: ksc-employee-mock
  replicas: 1
  template:
    metadata:
      labels:
        app: ksc-employee-mock
    spec:
      containers:
      - name: ksc-employee-mock
        image: ghcr.io/pgschk/ksc-employee-mock:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 20Mi
            cpu: 50m
          limits:
            memory: 50Mi
            cpu: 100m
        readinessProbe:
          httpGet:
            path: /v1/employees
            port: 8080
          failureThreshold: 3
          periodSeconds: 10
          initialDelaySeconds: 10
      restartPolicy: Always
