###################################
# Build and publish image to GHCR #
###################################

name: Build and Publish
on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "README.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Build ksc-employee-mock
        run: docker build . --tag ghcr.io/pgschk/ksc-employee-mock:latest

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish ksc-employee-mock to GHCR
        run: docker push ghcr.io/pgschk/ksc-employee-mock:latest
